format = """$directory$aws$pulumi$git_branch$git_status$cmd_duration$fill$kubernetes$line_break$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "

[fill]
symbol = " "

[directory]
style = "bg:#4db8ff fg:black"
format = "[$path ]($style)[$read_only]($read_only_style)[](fg:#4db8ff bg:black)"

[aws]
format = '[$symbol($profile )(\($region\) )]($style)[](fg:#FFFFFF bg:black)'
style = "bg:#A020F0 fg:white"
symbol = "AWS☁️  "

[pulumi]
style = "bg:#ff33ff fg:black"
format = "[ $stack ]($style)[](fg:#ff33ff bg:black)"

[git_branch]
symbol = " "
truncation_length = 20
truncation_symbol = "…"
style = "bg:#06d400 fg:black "
format = "[ $symbol$branch ]($style)[](fg:#06d400)"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
format = '([\[$all_status$ahead_behind\] ]($style))'
style = "bg:black fg:#06d400"

[kubernetes]
format = '[](fg:#326ce5 bg:black)[Kub☸️: $context/$namespace](bg:#326ce5 fg:#FFFFFF)[](fg:black bg:#326ce5) '
disabled = false

[nodejs]
format = "[:robot_face: $version](bold green) "
disabled = true

[package]
format = "[:gift: $version](208 bold) "
disabled = true

[cmd_duration]
disabled = false

